### ISSUE TITLE
Darwin: Compilation error

### ISSUE THREAD

**Issue by pierre-emmanuelJ** [motet-a/toy#1]
Hello, very nice funny project!

I have an issue with `struct stack`, I think it's just a little conflict

```C
vm.c:65:22: error: typedef redefinition with different types ('struct stack' vs 'struct __darwin_sigaltstack')
typedef struct stack stack_t;
                     ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/sys/_types/_sigaltstack.h:48:29: note: previous definition is here
typedef _STRUCT_SIGALTSTACK     stack_t; /* [???] signal stack */
                                ^
vm.c:75:17: error: no member named 'size' in 'struct __darwin_sigaltstack'
    if (!stack->size) {
         ~~~~~  ^
```

**Comment by motet-a** [comment]
Hello,

Thanks for pointing out this issue. I think the best way to solve this is to prefix every symbol by something like `toy_`. Naming conflicts are an inherent issue of the C language.

**Comment by motet-a** [comment]
In fact this `stack_t` type is defined for the `sigaltstack(2)` syscall, which conforms to POSIX. It’s just that for some reason, including `stdlib.h` on macOS does include `sigaltstack(2)` headers too, so… only renaming `stackk_t` isn’t a bad idea.

**Comment by pierre-emmanuelJ** [comment]
yes or something like `toy_stack_t` or `stack_toy_t`
